name: autotomi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get:
  figma_squircle: ^0.5.3
  flutter_svg:
  pinput: ^3.0.1
  get_storage: ^2.1.1
  intl_phone_field: ^3.1.0
  image_picker:
  permission_handler: ^11.0.1
  animate_do:
  country_picker:
  percent_indicator: ^4.2.3
  card_swiper: ^3.0.1
  intl: ^0.18.1
  url_launcher:
  flick_video_player: ^0.5.0
  video_player: ^2.5.3
  fluttertoast: ^8.2.2
  flutter_rating_bar: ^4.0.1
  connectivity_plus: ^5.0.1
  dio: ^5.3.3
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  firebase_messaging: ^14.6.5
  device_info_plus:
  firebase_core: ^2.15.0
  modal_progress_hud_nsn: ^0.4.0
  google_sign_in: ^6.1.4
  firebase_auth: ^4.7.1
  sign_in_with_apple: ^5.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1
  flutter_stripe:
  http: ^1.1.0
  timeago: ^3.4.0
  grouped_list: ^5.1.2
  flutter_local_notifications: ^9.9.1
#  awesome_notifications: ^0.8.2
  cloud_firestore: ^4.12.1
  flutter: 
    sdk: flutter

dev_dependencies: 
#  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/video/


  fonts:
    - family: Regular
      fonts:
         - asset: assets/fonts/Urbanist-Regular.ttf
    - family: Medium
      fonts:
         - asset: assets/fonts/Urbanist-Medium.ttf
    - family: SemiBold
      fonts:
         - asset: assets/fonts/Urbanist-SemiBold.ttf
    - family: Bold
      fonts:
         - asset: assets/fonts/Urbanist-Bold.ttf

